CREATE TABLE "t_zan_cai_record"(
"_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"news_type" TEXT,
"news_id" TEXT,
"has_zan" INTEGER,
"has_cai" INTEGER);

CREATE TABLE "t_hero"(
"_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"hero_id" INTEGER,
"hero_name" TEXT,
"_u_nation_type" TEXT,
"hero_icon" TEXT,
"_fdifficulty" TEXT,
"_fbattle" TEXT,
"_fposition" TEXT,
"_type1" TEXT,
"_type2" TEXT,
"_difficulty" INTEGER,
"_survial" INTEGER,
"_physics" INTEGER,
"_technology" INTEGER,
"hero_desc" TEXT,
"attack" TEXT,
"armor" TEXT,
"speed" TEXT,
"strength" TEXT,
"agility" TEXT,
"intelligence" TEXT,

"skill1_name" TEXT,
"skill1_icon" TEXT,
"skill1_scope" TEXT,
"skill1_effect" TEXT,
"skill1_magic" TEXT,
"skill1_c_d" TEXT,
"skill1_level1_effect" TEXT,
"skill1_level2_effect" TEXT,
"skill1_level3_effect" TEXT,
"skill1_level4_effect" TEXT,

"skill2_name" TEXT,
"skill2_icon" TEXT,
"skill2_scope" TEXT,
"skill2_effect" TEXT,
"skill2_magic" TEXT,
"skill2_c_d" TEXT,
"skill2_level1_effect" TEXT,
"skill2_level2_effect" TEXT,
"skill2_level3_effect" TEXT,
"skill2_level4_effect" TEXT,

"skill3_name" TEXT,
"skill3_icon" TEXT,
"skill3_scope" TEXT,
"skill3_effect" TEXT,
"skill3_magic" TEXT,
"skill3_c_d" TEXT,
"skill3_level1_effect" TEXT,
"skill3_level2_effect" TEXT,
"skill3_level3_effect" TEXT,
"skill3_level4_effect" TEXT,

"skill4_name" TEXT,
"skill4_icon" TEXT,
"skill4_scope" TEXT,
"skill4_effect" TEXT,
"skill4_magic" TEXT,
"skill4_c_d" TEXT,
"skill4_level1_effect" TEXT,
"skill4_level2_effect" TEXT,
"skill4_level3_effect" TEXT,
"skill4_level4_effect" TEXT);